# Generated by nixos-generate-config; regenerate with `nixos-generate-config`.
# Keep hand-written config in default.nix so it survives regeneration.
{
  config,
  lib,
  ...
}: {
  boot.initrd.availableKernelModules = ["vmd" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/55B0-F077";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/57cfeea5-2c36-4ce5-9ae6-a9c90bb07fa8";
  boot.initrd.luks.devices."cryptmedia1".device = "/dev/disk/by-uuid/d8122567-0284-4989-8402-4d36a358f75d";
  boot.initrd.luks.devices."cryptmedia2".device = "/dev/disk/by-uuid/429508c1-d8a1-4385-b77b-6db7781add70";
  boot.initrd.luks.devices."cryptmedia3".device = "/dev/disk/by-uuid/548def7c-1f1a-47d5-8548-d9530a305f16";

  boot.swraid = {
    enable = true;
    mdadmConf = "ARRAY /dev/md0 metadata=1.2 UUID=f6d83731:c69c6cbc:668333c7:7aac033e";
  };
  boot.initrd.luks.devices."cryptmediaraid".device = "/dev/disk/by-uuid/c557383b-ccb2-4ff0-8f93-55a51872d924";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/47deaee9-9beb-4a16-b070-45f3cc76783f";
    fsType = "ext4";
  };

  fileSystems."/mnt/mediaraid1" = {
    device = "/dev/disk/by-uuid/aea0555d-7cee-401d-b173-0fbb85b8d83d";
    fsType = "ext4";
  };

  fileSystems."/mnt/media1" = {
    device = "/dev/disk/by-uuid/ee6a2939-61b3-43a1-9cd7-ced460c91f2b";
    fsType = "ext4";
  };

  fileSystems."/mnt/media2" = {
    device = "/dev/disk/by-uuid/b4a1e533-812f-4c54-8f53-590811536442";
    fsType = "ext4";
  };

  fileSystems."/mnt/media3" = {
    device = "/dev/disk/by-uuid/ac1168df-4e9c-4cf7-8d83-dcee9f73910f";
    fsType = "ext4";
  };

  fileSystems."/media" = {
    device = "/mnt/media1:/mnt/mediaraid1:/mnt/media3";
    fsType = "fuse.mergerfs";
    options = [
      "defaults"
      "allow_other"
      "use_ino"
      "cache.files=off"
      "dropcacheonclose=true"
      "category.create=epmfs"
      "minfreespace=25G"
    ];
  };

  swapDevices = [];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
