# Generated by nixos-generate-config; regenerate with `nixos-generate-config`.
# Keep hand-written config in default.nix so it survives regeneration.
{
  config,
  lib,
  ...
}: {
  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = ["amdgpu"];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/effbb375-18d4-4948-8813-8e72bf66fb8e";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-dba8fa5f-bee4-4336-b85a-ee95fb08b755".device = "/dev/disk/by-uuid/dba8fa5f-bee4-4336-b85a-ee95fb08b755";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C8FB-6B76";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  networking.useDHCP = lib.mkDefault true;

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
