[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_branch]
style = 'bold blue'

[python]
symbol = '󰌠 '

[hostname]
format = '[$ssh_symbol](bold blue)on [$hostname](bold red) '
disabled = false
