# Generated by nixos-generate-config; regenerate with `nixos-generate-config`.
# Keep hand-written config in default.nix so it survives regeneration.
{
  config,
  lib,
  ...
}: {
  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  services.fstrim.enable = lib.mkDefault true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/469f1b05-3c7b-41bf-8e11-697e29149272";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9619-E48A";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/2b8d103b-57dc-4f77-afa1-da3ed9b9277f";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."crypt-home".device = "/dev/disk/by-uuid/d25441a4-17cb-4fc1-96b8-2df8700ed31c";

  swapDevices = [];

  networking.useDHCP = lib.mkDefault true;

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
