[ env ]
TERM = "xterm-256color"

[font]
size=8

[font.normal]
family = "JetbrainsMono Nerd Font"

[general]
#import = ["~/.config/alacritty/themes/themes/iterm.toml"]
#import = ["~/.config/alacritty/themes/themes/one_dark.toml"]
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[window]
opacity = 1
