[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
]

[font]
size=13

[font.normal]
family = "JetbrainsMono Nerd Font"

[window]
opacity = 0.9
